### ISSUE TITLE
Grid is not visible in any workspaces even after enabling it

### ISSUE THREAD

**Issue by Sadia2000** [flathub/org.freecad.FreeCAD#14]
Description: Trying to toggle on the grid view does not work in any of the workspaces provided by default as well as the new BIM Workspace. Tried both via keyboard shortcut (G) and via the graphical toolbar.

Operating system: Linux Mint 22
(previously also faced the same issue on Linux Mint 21.3)
FreeCAD version: 0.21.2 (build 33771) from Flatpak.

Reference image:
![image](https://github.com/user-attachments/assets/0826cb76-5275-451c-8039-0b78a53a2c12)

**Comment by adrianinsaval** [comment]
I'm not able to reproduce this in the latest stable or beta version and have not heard back from OP so will consider this solved, feel free to reopen if you are still experiencing this issue
