### ISSUE TITLE
Flatpak not yet verified creating confusion between 2 apps on flathub

### ISSUE THREAD

**Issue by Int-Circuit** [flathub/org.freecad.FreeCAD#16]
The freecad flatpak isn't yet verified, which could confuse new users when searching freecad on flatpak.

Verifying the app and adding a notice on the old app page could be a good idea.

**Comment by azzamsa** [comment]
I think the old version is deleted.

Before:

![image](https://github.com/user-attachments/assets/1f7227f7-1a8b-4d71-8ec5-180be9e99884)

Current:

![image](https://github.com/user-attachments/assets/6763ea89-aa25-4586-a60f-570d87363a7c)

**Comment by azzamsa** [comment]
Any reason for this migration?
