### ISSUE TITLE
A second Release Candidate is available

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.freecad.FreeCAD#3]
As per title, can this be updated to the current Release Candidate please?

TIA,
Neil Darlow

**Comment by hfiguiere** [comment]
It's already there

https://github.com/flathub/org.freecad.FreeCAD/blob/beta/org.freecad.FreeCAD.yaml#L782

**Comment by neildarlow** [comment]
OK. Thank you. The commit hash confirms that. The version string hadn't been updated in the About dialog. It still shows 1.0.0RC1.
