### ISSUE TITLE
AutoRecovery does not work

### ISSUE THREAD

**Issue by akvadrako** [flathub/org.freecad.FreeCAD#5]
Every time I open a document in FreeCAD, I see an error message like this:

> 16:53:53  Document with the UUID '2d38467b-cbb2-4db3-a735-3fc73eb2855c' already exists, change to 'e2cca819-bbd6-42e1-9ffe-930a332170db'

Because FreeCAD thinks it's a different document, AutoRecovery doesn't work.This seems to be because FreeCAD uses the PID as part of a lock file and that lockfile always has PID=2 in flatpak, so it thinks I'm opening a document with a duplicate UUID instead of the same document.

The lock file is `/home/dev/.var/app/org.freecadweb.FreeCAD/cache/FreeCAD/Cache/FreeCAD_2.lock`.

**Comment by adrianinsaval** [comment]
this has now been fixed upstream and will be available on flathub soon
